-- MySQL Script generated by MySQL Workbench
-- 07/01/20 15:16:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema fts
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema fts
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `fts` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `fts` ;

-- -----------------------------------------------------
-- Table `fts`.`produit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `fts`.`produit` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `designation` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NULL,
  `prix` VARCHAR(255) NOT NULL,
  `categorie` ENUM('ALIMENTATION', 'HABILLEMENT', 'BIJOUTERIE', 'QUINCAILLERIE', 'PHARMACIE') NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
